### ISSUE TITLE
¿Ayuda?

### ISSUE THREAD

**Issue by pablocloud** [Noneking/NakaDesingsApp#1]
Quieres que te ayude en algo? O que reduzca tu código? XD

**Comment by Noneking** [comment]
Eing?? Como sabes del proyecto?? Xd

**Comment by Noneking** [comment]
Joder x un momentl me has rayado mucho xd

**Comment by pablocloud** [comment]
XD, te tengo en github y me salen tus push

**Comment by Noneking** [comment]
ya, me he terminado dando cuenta xd. Mejor hablamos x whatsapp
